const PLANS = [
  {
    id: 'free',
    name: 'Free',
    price: '$0',
    period: 'forever',
    scans: 3,
    scanLabel: '3 scans total',
    features: [
      '3 lifetime scans',
      'Basic signal output',
      'Scanner tab only',
      'No alerts',
    ],
    cta: 'Current Plan',
    ctaDisabled: true,
    color: '#5a6370',
    accent: 'rgba(90,99,112,0.15)',
    border: 'rgba(90,99,112,0.25)',
  },
  {
    id: 'standard',
    name: 'Standard',
    price: '$25',
    period: 'one-time purchase',
    scans: 20,
    scanLabel: '20 scans',
    features: [
      '20 scan credits',
      'Full AI analysis',
      'Multi-TF scanner',
      'Push alerts',
      'Watchlist',
    ],
    cta: 'Buy Standard',
    ctaDisabled: false,
    url: 'https://paystack.com/buy/app-scanner--standard--gxfshu',
    color: '#00bcd4',
    accent: 'rgba(0,188,212,0.08)',
    border: 'rgba(0,188,212,0.3)',
    badge: null,
  },
  {
    id: 'premium',
    name: 'Premium',
    price: '$100',
    period: 'per year',
    scans: -1,
    scanLabel: 'Unlimited scans',
    features: [
      'Unlimited scans / year',
      'Full AI analysis',
      'Multi-TF scanner',
      'Push alerts',
      'Watchlist',
      'Priority support',
      'Early access to features',
    ],
    cta: 'Buy Premium',
    ctaDisabled: false,
    url: 'https://paystack.com/buy/app-scanner--premium--onvowo',
    color: '#00e676',
    accent: 'rgba(0,230,118,0.08)',
    border: 'rgba(0,230,118,0.35)',
    badge: 'BEST VALUE',
  },
]
